name: Feature List Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run every night at midnight UTC
  workflow_dispatch:  

jobs:
  check-and-update-features:
    runs-on: ubuntu-latest
    env:
      FEATURES_FILE: 'data/features.json'

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Check for updates in source repository
        id: check-updates
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GH_ACCESS_TOKEN}}
          script: |
            const { data: sourceFile } = await github.rest.repos.getContent({
              owner: 'layer5labs',
              repo: 'meshery-extensions-packages',
              path: 'feature-data.json',
              ref: 'master'
            });
            
            // Store the latest commit SHA
            const latestSHA = sourceFile.sha;
            
            // Try to get the previously stored SHA from cache
            const cache = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            let hasUpdates = true;
            if (cache.data.actions_caches.length > 0) {
              const lastSHA = cache.data.actions_caches[0].key.split('-').pop();
              hasUpdates = lastSHA !== latestSHA;
            }
            
            if (hasUpdates) {
              // Update the cache with new SHA
              await github.rest.actions.createActionsCacheEntry({
                owner: context.repo.owner,
                repo: context.repo.repo,
                key: `feature-data-sha-${latestSHA}`,
                ref: context.ref,
                cache_data: latestSHA
              });
              
              // Decode and save the content
              const content = Buffer.from(sourceFile.content, 'base64').toString('utf-8');
              const fs = require('fs');
              
              // Create data directory if it doesn't exist
              fs.mkdirSync('data', { recursive: true });
              
              // Write the new content
              fs.writeFileSync('${{ env.FEATURES_FILE }}', content);
            }
            
            return hasUpdates;

      - name: Commit changes
        if: steps.check-updates.outputs.result == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated feature data from source repository"
          file_pattern: ${{ env.FEATURES_FILE }}
          branch: master
          commit_options: "--signoff"
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>