name: Feature List

on:
  workflow_dispatch:
    inputs:
      spreadsheet_uri:
        description: 'Link of the spreadsheet containing subscription details.'
        type: string
        required: true

jobs:
  update-feature-data:
    runs-on: ubuntu-latest
    env:  
      FEATURES_FILE: 'data/features.json'  

    steps:
      - name: Trigger Feature List workflow and wait for completion
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GH_ACCESS_TOKEN}}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'layer5labs',
              repo: 'meshery-extensions-packages',
              workflow_id: 'generate-feature-list.yml',
              ref: 'master',
              inputs: {
                spreadsheet_uri: '${{ secrets.INPUT_SPREADSHEET_URI }}'
              }
            });
            
            console.log("Triggered workflow, waiting for completion...");
            
            while (true) {
              const runs = await github.rest.actions.listWorkflowRuns({
                owner: 'layer5labs',
                repo: 'meshery-extensions-packages',
                workflow_id: 'generate-feature-list.yml'
              });
              
              if (runs.data.workflow_runs[0].status === 'completed') {
                console.log("Workflow completed");
                break;
              }
              
              console.log("Waiting for workflow to complete...");
              await new Promise(resolve => setTimeout(resolve, 30000));
            }

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create data directory if it doesn't exist
        run: mkdir -p data

      - name: Download new feature data
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GH_ACCESS_TOKEN}}
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const { data } = await github.rest.repos.getContent({
              owner: 'layer5labs',
              repo: 'meshery-extensions-packages',
              path: 'feature-data.json'
            });
            
            const newContent = Buffer.from(data.content, 'base64').toString('utf-8');
            fs.writeFileSync('${{ env.FEATURES_FILE }}', newContent);

      - name: Update or create features.json
        run: |
          if [ -f "${{ env.FEATURES_FILE }}" ]; then
            echo "Updating existing features.json"
          else
            echo "Creating new features.json"
            cp "${{ env.FEATURES_FILE }}" data/features.json
          fi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated feature data
          file_pattern: ${{ env.FEATURES_FILE }}
          branch: master
          commit_options: "--signoff"
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>