name: Nightly Google Sheet Check

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Google Sheet updates
        id: sheet-check
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GH_ACCESS_TOKEN}}
          script: |
            const { GoogleSpreadsheet } = require('google-spreadsheet');
            
            async function checkForUpdates() {
              const doc = new GoogleSpreadsheet('${{ secrets.INPUT_SPREADSHEET_URI }}');
              await doc.useServiceAccountAuth({
                client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
                private_key: process.env.GOOGLE_PRIVATE_KEY,
              });
              
              await doc.loadInfo();
              const sheet = doc.sheetsByIndex[0];
              const lastModified = sheet.lastModified;
              
              const cache = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              
              let lastKnownModified = null;
              if (cache.data.actions_caches.length > 0) {
                lastKnownModified = new Date(cache.data.actions_caches[0].last_accessed_at);
              }
              
              if (!lastKnownModified || lastModified > lastKnownModified) {
                await github.rest.actions.createActionsCacheEntry({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  key: 'last-modified-time',
                  ref: context.ref,
                  cache_data: lastModified.toISOString(),
                });
                return true;
              }
              
              return false;
            }
            
            const hasUpdates = await checkForUpdates();
            core.setOutput('has-updates', hasUpdates);

      - name: Trigger Subscriptions Plan workflow
        if: steps.sheet-check.outputs.has-updates == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GH_ACCESS_TOKEN}}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'feature-list.yml',
              ref: 'main',
              inputs: {
                spreadsheet_uri: '${{ secrets.INPUT_SPREADSHEET_URI }}'
              }
            });