name: Release Chart
on:
  # Only release when called by stable release workflow
  # push:
  #   branches:
  #     - 'master'
  #   tags:
  #     - 'v*'
  #   paths:
  #     - 'install/kubernetes/**'
  #   pull_request:
  #     branches:
  #       - 'master'
  #     paths:
  #       - 'install/kubernetes/**'
  workflow_call:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      release-ver:
        description: "Release Version"
        required: false
        default: "v0.7.83"
jobs:
  validate:
    runs-on: ubuntu-latest
    # if: ${{github.event_name == 'pull_request'}}
    steps:
      - uses: actions/checkout@v4
        with:
          path: cloud
          repository: layer5io/meshery-cloud
          ref: master
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: actions/checkout@v4
        with:
          path: docs
          repository: layer5io/docs
          ref: master
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: azure/setup-helm@v4.1.0
      - name: validate
        run: helm lint cloud/install/kubernetes --with-subcharts
      - name: Change to cloud directory
        run: |
          cd cloud;
      - name: Manually publish Helm chart with release version
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          charts_dir: meshery-cloud/install/kubernetes